name: Build TF

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_upload_darwin_x86_64:
    name: Build and upload libtensorflow.dylib and libtensorflowlite_c.dylib on darwin_x86_64 platform
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build darwin_x86_64 package
        shell: bash
        run: |
          brew install python
          pip3 install -U --user pip numpy wheel
          pip3 install -U --user keras_preprocessing --no-deps
          git clone -b v2.6.0 https://github.com/tensorflow/tensorflow.git tensorflow_src
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-darwin-amd64
          chmod u+x bazelisk-darwin-amd64
          mv bazelisk-darwin-amd64 /usr/local/bin
          cd tensorflow_src
          export CC=clang
          export CXX=clang++
          PYTHON_BIN_PATH=/usr/local/opt/python@3.11/bin/python3.11 USE_DEFAULT_PYTHON_LIB_PATH=1 TF_NEED_CUDA=0 TF_NEED_ROCM=0 TF_DOWNLOAD_CLANG=0 TF_NEED_MPI=0 CC_OPT_FLAGS="-march=native -Wno-sign-compare" TF_SET_ANDROID_WORKSPACE=0 TF_CONFIGURE_IOS=0 ./configure
          bazel build -c opt //tensorflow:libtensorflow_cc.dylib
          bazel build -c opt //tensorflow/lite/c:libtensorflowlite_c.dylib
          cd ..
          cp tensorflow_src/bazel-bin/tensorflow/lite/c/libtensorflowlite_c.dylib libtensorflowlite_c.dylib
          tar -zcvf tflite.tar.gz libtensorflowlite_c.dylib
          cp tensorflow_src/bazel-bin/tensorflow/libtensorflow_cc.2.6.0.dylib libtensorflow_cc.2.6.0.dylib
          cp tensorflow_src/bazel-bin/tensorflow/libtensorflow_framework.2.6.0.dylib libtensorflow_framework.2.6.0.dylib
          tar -zcvf tf.tar.gz libtensorflow_cc.2.6.0.dylib libtensorflow_framework.2.6.0.dylib
      - name: Upload artifact TF
        uses: actions/upload-artifact@v3
        with:
          name: WasmEdge-tensorflow-deps-TF-darwin_x86_64.tar.gz
          path: tf.tar.gz
      - name: Upload artifact TFLite
        uses: actions/upload-artifact@v3
        with:
          name: WasmEdge-tensorflow-deps-TFLite-darwin_x86_64.tar.gz
          path: tflite.tar.gz
